export type Element = {
  atomicNumber: number,
  element: string,
  symbol: string,
  atomicMass: number,
  numberofNeutrons: number,
  numberofProtons: number,
  numberofElectrons: number,
  period: number,
  group: number,
  phase: string,
  radioactive: string,
  natural: string,
  metal: string,
  nonmetal: string,
  metalloid: string,
  type: string,
  atomicRadius: number | string,
  electronegativity: number | string,
  firstIonization: number | string,
  density: number | string,
  meltingPoint: number | string,
  boilingPoint: number | string,
  numberOfIsotopes: number | string,
  discoverer: string,
  year: number | string,
  specificHeat: number | string,
  numberofShells: number,
  numberofValence: number | string,

  dontShow?: boolean,
  color: string,
  focus?: boolean
};